server:
  port: 8080

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    reservation: 
      path: /reservations/**
      serviceId: reservation-service
#    customer: 
#      path: /customer/**
#      serviceId: customer-service          

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG